# Generated by Django 5.2.14 on 2026-05-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Note'),
        ),
    ]
