# Generated by BlackboxAI on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="status",
            field=models.CharField(
                db_index=True,
                max_length=10,
                default="active",
                choices=[
                    ("active", "Active"),
                    ("frozen", "Frozen"),
                ],
                verbose_name="Account status",
            ),
            preserve_default=False,
        ),
    ]

