# Generated by Django 5.2.14 on 2026-06-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen')], db_index=True, default='active', max_length=10, verbose_name='Account status'),
        ),
    ]
